theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true
auto-pairs = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
