[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "markdown"
language-servers = [ "marksman" ]

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", outputPath = "$root/$name" }

[[language]]
name = "typst"
language-servers = ["tinymist"]






