#!/bin/sh

# executables to run off start
pgrep -x sxhkd > /dev/null || sxhkd &
#/usr/lib/xfce-polkit/xfce-polkit &
/home/crem/Documents/dots/nix/custom-scripts/polybar.launch.sh
# make the default cursor the left cursor
xsetroot -cursor_name left_ptr &
# fix burp window issue
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
